import json
import logging
import re

INPUT_PATH = "role_descriptions.json"
OUTPUT_PATH = "role_descriptions.md"
ADDONINFO_PATH = "Addoninfo.cs"
ROLE_COLOR_PATH = "role_color.json"  # generated by generate_addon_color.py
ROLE_SOURCE_COLOR_PATH = "role_source_color.json"  # generated by generate_role_source_color.py
LOG_PATH = "generate_md.log"

# CSV上の値が未整備の遺物などmd生成から除外したいrole id
EXCLUDED_ROLES = {
    "GhostRole",  # nameが"GhostRoll"のまま(翻訳/説明未整備)
}

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s: %(message)s",
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler(LOG_PATH, mode="w", encoding="utf-8"),
    ],
)
logger = logging.getLogger(__name__)

# <#ff1919>text</color> or <color=#ff1919>text</color> -> ${\textsf{\color{#ff1919}text}}$
# (GitHub-flavored KaTeX color)
COLOR_TAG_PATTERN = re.compile(r"<(?:color=)?#([0-9A-Fa-f]{6})>(.*?)</color>")

MARK_PATTERN = re.compile(r"CustomRoles\.(\w+)\s*=>\s*\"([^\"]*)\"")

# GitHub's math rendering doesn't reliably recognize a "$" that's glued directly to
# preceding text; require a half-width space (or start of line) right before every "$".
DOLLAR_NEEDS_SPACE_PATTERN = re.compile(r"(?<=[^ \n])\$")


def convert_color_tags(text):
    text = COLOR_TAG_PATTERN.sub(r"${\\textsf{\\color{#\1}\2}}$", text)
    text = text.replace("</color>", "")  # drop any unmatched stray closing tags
    text = DOLLAR_NEEDS_SPACE_PATTERN.sub(" $", text)
    return text


logger.info("%s を読み込み: 役職名/タグ/説明文の一覧として使用 (main)", INPUT_PATH)
with open(INPUT_PATH, encoding="utf-8") as f:
    roles = json.load(f)

logger.info("%s を読み込み: 属性マーク(記号)の抽出に使用 (MARK_PATTERN)", ADDONINFO_PATH)
with open(ADDONINFO_PATH, encoding="utf-8") as f:
    addoninfo = f.read()

marks = dict(MARK_PATTERN.findall(addoninfo))

logger.info("%s を読み込み: Addon/属性役職の色として使用 (colors)", ROLE_COLOR_PATH)
with open(ROLE_COLOR_PATH, encoding="utf-8") as f:
    colors = json.load(f)

logger.info("%s を読み込み: 役職本体の色として使用、colorsより優先 (colors)", ROLE_SOURCE_COLOR_PATH)
with open(ROLE_SOURCE_COLOR_PATH, encoding="utf-8") as f:
    source_colors = json.load(f)

# role's own source color takes precedence; addon/attribute color as fallback
colors = {**colors, **source_colors}

lines = []
current_tag = None

for role, data in roles.items():
    if role in EXCLUDED_ROLES:
        continue

    tag = data.get("tag")
    if tag == "TaskBattle":
        continue

    if tag != current_tag:
        lines.append(f"# {tag}")
        lines.append("")
        current_tag = tag

    description = data.get("long_description") or data.get("short_description") or ""
    description = description.replace("\\n", "\n")
    description = convert_color_tags(description)

    name = convert_color_tags(data.get("name") or "")
    mark = marks.get(role, "")
    color = colors.get(role)

    if not color:
        logger.warning("色が取得できませんでした: %s (%s)", role, data.get("name"))

    # KaTeX binds some unicode symbols (e.g. "∑") to math-only macros, so they
    # error out inside \textsf{} (text mode). Keep the mark in math mode and
    # only put the (CJK) name in \textsf, both nested under the same \color.
    # The mark goes after the name, separated by two half-width spaces.
    if color:
        inner = f"\\textsf{{{name}}}~~{mark}" if mark else f"\\textsf{{{name}}}"
        display_name = f"${{\\color{{{color}}}{inner}}}$"
    else:
        display_name = f"{name}  {mark}" if mark else name

    lines.append(f"## {display_name}")
    lines.append("")
    lines.append(description)
    lines.append("")

with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
