import json

ROLE_DESCRIPTIONS_PATH = "role_descriptions.json"
ROLE_SOURCE_COLOR_PATH = "role_source_color.json"  # generated by generate_role_source_color.py
OUTPUT_PATH = "source_roles.txt"

with open(ROLE_DESCRIPTIONS_PATH, encoding="utf-8") as f:
    roles = json.load(f)

with open(ROLE_SOURCE_COLOR_PATH, encoding="utf-8") as f:
    source_roles = json.load(f)

defined = sorted(source_roles.keys())
not_found = sorted(role for role in roles if role not in source_roles)

lines = [f"ソースで定義済み ({len(defined)}件)"]
lines += [f"- {role}" for role in defined]
lines.append("")
lines.append(f"ソースに定義が見つからなかった ({len(not_found)}件)")
lines += [f"- {role} ({roles[role].get('name')})" for role in not_found]

with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"defined: {len(defined)}, not found: {len(not_found)}")
